services:
  # 1. SERVER LARAVEL (BACKEND)
  backend-laravel:
    build:
      context: ./laravel
    container_name: app-backend
    ports:
      - "8000:8000"         
      - "5173:5173"         
    volumes:
      - ./laravel:/var/www/html
    command: php artisan serve --host=0.0.0.0 --port=8000
    depends_on:
      - app-db

  # 2. SERVER IONIC (FRONTEND)
  frontend-ionic:
    build:
      context: ./IONIC      
    container_name: app-frontend
    ports:
      - "8100:8100"         
    volumes:
      - ./IONIC:/app
      - /app/node_modules   

  # 3. DATABASE (MYSQL)
  app-db:
    image: mysql:8.0
    container_name: app-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"        
    volumes:
      - db_master_data:/var/lib/mysql

  # 4. DATABASE MANAGER (PHPMYADMIN)
  app-phpmyadmin:
    image: phpmyadmin:latest
    container_name: app-pma
    restart: always
    ports:
      - "8080:80"         
    environment:
      PMA_HOST: app-db
    depends_on:
      - app-db

volumes:
  db_master_data: